// <auto-generated />
namespace tip4trip_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Me_lathos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Me_lathos));
        
        string IMigrationMetadata.Id
        {
            get { return "201904171744300_Me_lathos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
