// <auto-generated />
namespace tip4trip_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deca));
        
        string IMigrationMetadata.Id
        {
            get { return "201904181620157_Deca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
